apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: app-izaias
  name: app-izaias
  namespace: aluno-izaias
spec:
  podMetricsEndpoints:
  - port: 
      number: 5000
    interval: 10s
  selector:
    matchLabels:
      app: app-izaias
